// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64
	Name string
	Bio  pgtype.Text
}

type User struct {
	ID               pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
	Deleted          bool
	Verified         bool
	Deactivated      bool
	Private          bool
	Approved         bool
	Email            pgtype.Text
	Username         string
	Password         string
	TwoFactorEnabled bool
	TwoFactorSecret  pgtype.Text
	RecoveryCodes    []byte
	UsernameChange   pgtype.Timestamptz
	UsernameChanged  pgtype.Bool
	DeactivatedOn    pgtype.Timestamptz
	ReactivatedOn    pgtype.Timestamptz
	Suspended        bool
	SuspendedOn      pgtype.Timestamptz
	Settings         []byte
	About            pgtype.Text
	Image            pgtype.Text
	Tsv              interface{}
	Name             pgtype.Text
	Bot              bool
	Unlisted         bool
	Nsfw             bool
	Meta             []byte
}
